def exception_handler(Exception):
    return None